### ISSUE TITLE
Null Reference Exception on startup

### ISSUE THREAD

**Issue by scmcgowen** [Ale32bit/REPSbox#1]
![Image](https://github.com/user-attachments/assets/87afd4b1-3e72-47a0-a652-53528f2f709a)
The only change I have made was replacing `wss://chat.reconnected.cc/v2/` with `ws://cogs.maplemod.works:25678/` in ChatBot.cs. That way it runs for that other server

**Comment by thrailkillr** [comment]
> ![Image](https://github.com/user-attachments/assets/87afd4b1-3e72-47a0-a652-53528f2f709a) The only change I have made was replacing `wss://chat.reconnected.cc/v2/` with `ws://cogs.maplemod.works:25678/` in ChatBot.cs. That way it runs for that other server

Try with SSL? Caddy is free.

**Comment by scmcgowen** [comment]
It wasn't related to that. 
This docker compose setup worked
```yml
services:
  repsbox:
    image: ghcr.io/ale32bit/repsbox:main
    container_name: repsbox
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```
Only change I made there was switching to my own local build because GitHub didn't build it instantly
